name: 'coverage'
on:
    pull_request:
        branches:
            - master
            - main
jobs:
    coverage:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage-badge
      - name: Build coverage file
        run: |
          pytest --cache-clear --cov=app/test/ --cov-fail-under=80 > pytest-coverage.txt
      - name: Comment coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2

      - name: Coverage Badge
        run: coverage-badge > coverage.svg
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
            force_with_lease: true
            github_token: ${{ secrets.TOKEN }}
            branch: ${{ github.ref }}
